version: '2'
services:
  inochidemo3-app:
    image: inochidemo3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://inochidemo3-mariadb:3306/inochidemo3
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://inochidemo3-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://inochidemo3-elasticsearch:9200
    ports:
      - 8080:8080
  inochidemo3-mariadb:
    extends:
      file: mariadb.yml
      service: inochidemo3-mariadb
  inochidemo3-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: inochidemo3-elasticsearch
